name: Import Solution using a settings file
run-name: Packing ${{ github.event.inputs.solution_name }} for ${{ github.event.inputs.environment_url }} environment
on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: "name of the Solution"
        required: true
        default: MMC_Test
      environment_url:
        description: "http endpoint of your Dataverse environment"
        required: true
        default: "https://org8f174b27.crm.dynamics.com/"  # Test Environment URL
env:
#edit your values here
  CLIENT_ID: '853d3271-4006-4e67-a512-0ab4159969f7'
  TENANT_ID: '2b0463ed-efd7-419d-927d-a9dca49d899c'

permissions:
  contents: write
  
jobs:
    pack-umanaged-solution-import:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
        env:
          RUNNER_DEBUG: 1
      
       
      - name: Pack the solution to import
        uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-folder: out/solutions/${{ github.event.inputs.solution_name }}
          solution-file: out/exported/${{ github.event.inputs.solution_name }}.zip 
          solution-type: Unanaged
    
      - name: Import solution to Test env using the settings file
        uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          environment-url: ${{github.event.inputs.environment_url}}
          app-id: ${{env.CLIENT_ID}}
          client-secret: ${{ secrets.PowerPlatformSPN }}
          tenant-id: ${{env.TENANT_ID}}
          solution-file: out/exported/${{ github.event.inputs.solution_name }}.zip 
          use-deployment-settings-file: true
          deployment-settings-file: out/exported/${{ github.event.inputs.solution_name }}.json
          force-overwrite: true
          publish-changes: true
